/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardPostsRouteImport } from './routes/dashboard.posts'
import { Route as DashboardBackupsRouteImport } from './routes/dashboard.backups'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as DashboardSchedulingIndexRouteImport } from './routes/dashboard.scheduling.index'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard.posts.index'
import { Route as DashboardSettingsStorageRouteImport } from './routes/dashboard.settings.storage'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard.settings.security'
import { Route as DashboardSchedulingRetentionRouteImport } from './routes/dashboard.scheduling.retention'
import { Route as DashboardSchedulingNotificationsRouteImport } from './routes/dashboard.scheduling.notifications'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard.projects.new'
import { Route as DashboardProjectsImportRouteImport } from './routes/dashboard.projects.import'
import { Route as DashboardPostsPostIdRouteImport } from './routes/dashboard.posts.$postId'
import { Route as DashboardBackupsScheduledRouteImport } from './routes/dashboard.backups.scheduled'
import { Route as DashboardBackupsRestoreRouteImport } from './routes/dashboard.backups.restore'
import { Route as DashboardBackupsManualRouteImport } from './routes/dashboard.backups.manual'
import { Route as DashboardBackupsHistoryRouteImport } from './routes/dashboard.backups.history'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostsRoute = DashboardPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSchedulingIndexRoute =
  DashboardSchedulingIndexRouteImport.update({
    id: '/scheduling/',
    path: '/scheduling/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardPostsRoute,
} as any)
const DashboardSettingsStorageRoute =
  DashboardSettingsStorageRouteImport.update({
    id: '/settings/storage',
    path: '/settings/storage',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSchedulingRetentionRoute =
  DashboardSchedulingRetentionRouteImport.update({
    id: '/scheduling/retention',
    path: '/scheduling/retention',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSchedulingNotificationsRoute =
  DashboardSchedulingNotificationsRouteImport.update({
    id: '/scheduling/notifications',
    path: '/scheduling/notifications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsImportRoute = DashboardProjectsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardPostsPostIdRoute = DashboardPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => DashboardPostsRoute,
} as any)
const DashboardBackupsScheduledRoute =
  DashboardBackupsScheduledRouteImport.update({
    id: '/scheduled',
    path: '/scheduled',
    getParentRoute: () => DashboardBackupsRoute,
  } as any)
const DashboardBackupsRestoreRoute = DashboardBackupsRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => DashboardBackupsRoute,
} as any)
const DashboardBackupsManualRoute = DashboardBackupsManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => DashboardBackupsRoute,
} as any)
const DashboardBackupsHistoryRoute = DashboardBackupsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardBackupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backups': typeof DashboardBackupsRouteWithChildren
  '/dashboard/posts': typeof DashboardPostsRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/backups/history': typeof DashboardBackupsHistoryRoute
  '/dashboard/backups/manual': typeof DashboardBackupsManualRoute
  '/dashboard/backups/restore': typeof DashboardBackupsRestoreRoute
  '/dashboard/backups/scheduled': typeof DashboardBackupsScheduledRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/dashboard/projects/import': typeof DashboardProjectsImportRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/scheduling/notifications': typeof DashboardSchedulingNotificationsRoute
  '/dashboard/scheduling/retention': typeof DashboardSchedulingRetentionRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/storage': typeof DashboardSettingsStorageRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/scheduling': typeof DashboardSchedulingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backups': typeof DashboardBackupsRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/backups/history': typeof DashboardBackupsHistoryRoute
  '/dashboard/backups/manual': typeof DashboardBackupsManualRoute
  '/dashboard/backups/restore': typeof DashboardBackupsRestoreRoute
  '/dashboard/backups/scheduled': typeof DashboardBackupsScheduledRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/dashboard/projects/import': typeof DashboardProjectsImportRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/scheduling/notifications': typeof DashboardSchedulingNotificationsRoute
  '/dashboard/scheduling/retention': typeof DashboardSchedulingRetentionRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/storage': typeof DashboardSettingsStorageRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/scheduling': typeof DashboardSchedulingIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/backups': typeof DashboardBackupsRouteWithChildren
  '/dashboard/posts': typeof DashboardPostsRouteWithChildren
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/backups/history': typeof DashboardBackupsHistoryRoute
  '/dashboard/backups/manual': typeof DashboardBackupsManualRoute
  '/dashboard/backups/restore': typeof DashboardBackupsRestoreRoute
  '/dashboard/backups/scheduled': typeof DashboardBackupsScheduledRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/dashboard/projects/import': typeof DashboardProjectsImportRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/scheduling/notifications': typeof DashboardSchedulingNotificationsRoute
  '/dashboard/scheduling/retention': typeof DashboardSchedulingRetentionRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/storage': typeof DashboardSettingsStorageRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/scheduling/': typeof DashboardSchedulingIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/backups'
    | '/dashboard/posts'
    | '/dashboard/projects'
    | '/dashboard/'
    | '/dashboard/backups/history'
    | '/dashboard/backups/manual'
    | '/dashboard/backups/restore'
    | '/dashboard/backups/scheduled'
    | '/dashboard/posts/$postId'
    | '/dashboard/projects/import'
    | '/dashboard/projects/new'
    | '/dashboard/scheduling/notifications'
    | '/dashboard/scheduling/retention'
    | '/dashboard/settings/security'
    | '/dashboard/settings/storage'
    | '/dashboard/posts/'
    | '/dashboard/projects/'
    | '/dashboard/scheduling'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/analytics'
    | '/dashboard/backups'
    | '/dashboard'
    | '/dashboard/backups/history'
    | '/dashboard/backups/manual'
    | '/dashboard/backups/restore'
    | '/dashboard/backups/scheduled'
    | '/dashboard/posts/$postId'
    | '/dashboard/projects/import'
    | '/dashboard/projects/new'
    | '/dashboard/scheduling/notifications'
    | '/dashboard/scheduling/retention'
    | '/dashboard/settings/security'
    | '/dashboard/settings/storage'
    | '/dashboard/posts'
    | '/dashboard/projects'
    | '/dashboard/scheduling'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/backups'
    | '/dashboard/posts'
    | '/dashboard/projects'
    | '/dashboard/'
    | '/dashboard/backups/history'
    | '/dashboard/backups/manual'
    | '/dashboard/backups/restore'
    | '/dashboard/backups/scheduled'
    | '/dashboard/posts/$postId'
    | '/dashboard/projects/import'
    | '/dashboard/projects/new'
    | '/dashboard/scheduling/notifications'
    | '/dashboard/scheduling/retention'
    | '/dashboard/settings/security'
    | '/dashboard/settings/storage'
    | '/dashboard/posts/'
    | '/dashboard/projects/'
    | '/dashboard/scheduling/'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/posts': {
      id: '/dashboard/posts'
      path: '/posts'
      fullPath: '/dashboard/posts'
      preLoaderRoute: typeof DashboardPostsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backups': {
      id: '/dashboard/backups'
      path: '/backups'
      fullPath: '/dashboard/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scheduling/': {
      id: '/dashboard/scheduling/'
      path: '/scheduling'
      fullPath: '/dashboard/scheduling'
      preLoaderRoute: typeof DashboardSchedulingIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardPostsRoute
    }
    '/dashboard/settings/storage': {
      id: '/dashboard/settings/storage'
      path: '/settings/storage'
      fullPath: '/dashboard/settings/storage'
      preLoaderRoute: typeof DashboardSettingsStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/settings/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scheduling/retention': {
      id: '/dashboard/scheduling/retention'
      path: '/scheduling/retention'
      fullPath: '/dashboard/scheduling/retention'
      preLoaderRoute: typeof DashboardSchedulingRetentionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scheduling/notifications': {
      id: '/dashboard/scheduling/notifications'
      path: '/scheduling/notifications'
      fullPath: '/dashboard/scheduling/notifications'
      preLoaderRoute: typeof DashboardSchedulingNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/import': {
      id: '/dashboard/projects/import'
      path: '/import'
      fullPath: '/dashboard/projects/import'
      preLoaderRoute: typeof DashboardProjectsImportRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/posts/$postId': {
      id: '/dashboard/posts/$postId'
      path: '/$postId'
      fullPath: '/dashboard/posts/$postId'
      preLoaderRoute: typeof DashboardPostsPostIdRouteImport
      parentRoute: typeof DashboardPostsRoute
    }
    '/dashboard/backups/scheduled': {
      id: '/dashboard/backups/scheduled'
      path: '/scheduled'
      fullPath: '/dashboard/backups/scheduled'
      preLoaderRoute: typeof DashboardBackupsScheduledRouteImport
      parentRoute: typeof DashboardBackupsRoute
    }
    '/dashboard/backups/restore': {
      id: '/dashboard/backups/restore'
      path: '/restore'
      fullPath: '/dashboard/backups/restore'
      preLoaderRoute: typeof DashboardBackupsRestoreRouteImport
      parentRoute: typeof DashboardBackupsRoute
    }
    '/dashboard/backups/manual': {
      id: '/dashboard/backups/manual'
      path: '/manual'
      fullPath: '/dashboard/backups/manual'
      preLoaderRoute: typeof DashboardBackupsManualRouteImport
      parentRoute: typeof DashboardBackupsRoute
    }
    '/dashboard/backups/history': {
      id: '/dashboard/backups/history'
      path: '/history'
      fullPath: '/dashboard/backups/history'
      preLoaderRoute: typeof DashboardBackupsHistoryRouteImport
      parentRoute: typeof DashboardBackupsRoute
    }
  }
}

interface DashboardBackupsRouteChildren {
  DashboardBackupsHistoryRoute: typeof DashboardBackupsHistoryRoute
  DashboardBackupsManualRoute: typeof DashboardBackupsManualRoute
  DashboardBackupsRestoreRoute: typeof DashboardBackupsRestoreRoute
  DashboardBackupsScheduledRoute: typeof DashboardBackupsScheduledRoute
}

const DashboardBackupsRouteChildren: DashboardBackupsRouteChildren = {
  DashboardBackupsHistoryRoute: DashboardBackupsHistoryRoute,
  DashboardBackupsManualRoute: DashboardBackupsManualRoute,
  DashboardBackupsRestoreRoute: DashboardBackupsRestoreRoute,
  DashboardBackupsScheduledRoute: DashboardBackupsScheduledRoute,
}

const DashboardBackupsRouteWithChildren =
  DashboardBackupsRoute._addFileChildren(DashboardBackupsRouteChildren)

interface DashboardPostsRouteChildren {
  DashboardPostsPostIdRoute: typeof DashboardPostsPostIdRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
}

const DashboardPostsRouteChildren: DashboardPostsRouteChildren = {
  DashboardPostsPostIdRoute: DashboardPostsPostIdRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
}

const DashboardPostsRouteWithChildren = DashboardPostsRoute._addFileChildren(
  DashboardPostsRouteChildren,
)

interface DashboardProjectsRouteChildren {
  DashboardProjectsImportRoute: typeof DashboardProjectsImportRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsImportRoute: DashboardProjectsImportRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBackupsRoute: typeof DashboardBackupsRouteWithChildren
  DashboardPostsRoute: typeof DashboardPostsRouteWithChildren
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSchedulingNotificationsRoute: typeof DashboardSchedulingNotificationsRoute
  DashboardSchedulingRetentionRoute: typeof DashboardSchedulingRetentionRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsStorageRoute: typeof DashboardSettingsStorageRoute
  DashboardSchedulingIndexRoute: typeof DashboardSchedulingIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBackupsRoute: DashboardBackupsRouteWithChildren,
  DashboardPostsRoute: DashboardPostsRouteWithChildren,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSchedulingNotificationsRoute: DashboardSchedulingNotificationsRoute,
  DashboardSchedulingRetentionRoute: DashboardSchedulingRetentionRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsStorageRoute: DashboardSettingsStorageRoute,
  DashboardSchedulingIndexRoute: DashboardSchedulingIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
